### ISSUE TITLE
ajuda na exibição dos dados

### ISSUE THREAD

**Issue by silva-andre** [epmallmann/MovideskApiClient#10]
Bom dia, utilizei a ferramenta para gerar os dados necessários para a empresa que trabalho com o código a baixo.

public async Task cliente()

        {

            ConfigurationManager.RefreshSection("AppSettings");
            string apikey = ConfigurationManager.AppSettings.Get("apikey");
            MovideskApiClientOptions options = new MovideskApiClientOptions { Token = apikey };
            MovideskClient client = new MovideskClient(new MovideskApiClient(options));
            var persons = await client.Tickets.Get(new OData 
            {
                Expand = "actions($select = origin, id),actions($expand = timeAppointments($expand = createdBy))",
                Filter = "actions/any(a: a/timeappointments/any(t: t/date ge 2020-12-01T00:00:00.00z and t/date le 2020-12-07T00:00:00.00z))",
                Select = "id,subject,createdDate",
                
            });
           
            dataGridView1.DataSource = persons.ResponseObject;
            lb_total.Text = dataGridView1.Rows.Count.ToString();

        }

porem na visualização aparece apenas os itens referente ao ticket, ele nao abre a array dos actions e timeAppointments, ficando da seguinte forma:

![image](https://user-images.githubusercontent.com/75839852/101908741-49db2380-3b9b-11eb-892b-7568b4d5e632.png)

queria saber se há a possibilidade do resulta no GridView tem como ser exibido semelhante ao do Excel da seguinte forma:

![image](https://user-images.githubusercontent.com/75839852/101909995-1e593880-3b9d-11eb-84d5-426f04a04f64.png)

fazendo aparecer tanto os tickets, actions, timeAppointments e createdBy dentro da mesmo DataTable no GridView

no mais agradeço a colaboração.

**Comment by epmallmann** [comment]
Olá.

Desconheço uma forma de realizar a apresentação.

Esta lib trata somente de um client para buscar os dados mesmo.

Obrigado.
