### ISSUE TITLE
Versão para VB.NET

### ISSUE THREAD

**Issue by clsaad** [epmallmann/MovideskApiClient#9]
boa Tarde!

Estamos implementando a biblioteca de voces mas usando em vb.net, porém ele força usar a versao 2.0 sempre do .net. E usamos a versao 4.5. Tem alguma recomendação?

Obrigado,

**Comment by epmallmann** [comment]
Olá.
VB.NET não é uma linguagem de meu conhecimento.

Este repositório é somente para a versão em dotnet mesmo.

Obrigado.
